main/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.core.validators import validate_email
from django.urls import path, include
from django.views.generic import TemplateView

from main.views import (
    ContestListView,
    ContestDetailView,
    ContestNomineesView,
    ParticipantView,
    like_nominees,
    ParticipantFavoriteView,
    ParticipantFormView,
    Winners,
    signup,
    activate,
    login_view,
    logout_view, UserDetailView,
    AdditionalView,
    export_excel,
    export_excel2,
)

urlpatterns = [
    path("", ContestListView.as_view(), name="homepage"),
    path("signup/", signup, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("activate/<uidb64>/<token>", activate, name="activate"),
    path("inside/<int:pk>/", ContestDetailView.as_view(), name="inside"),
    path('user/<int:pk>/', UserDetailView.as_view(), name="users"),
    path(
        "inside/<int:pk>/participants/", ContestNomineesView.as_view(), name="nominee"
    ),
    path(
        "inside/<int:pk>/favorites/", ParticipantFavoriteView.as_view(), name="favorite"
    ),
    path("inside/<int:pk>/winners/", Winners.as_view(), name="winners"),
    path("participant/<int:pk>/", ParticipantView.as_view(), name="nominee_detail"),
    path("ajax_like_nominees/<int:pk>/", like_nominees, name="like_nominee"),
    path("contest/participate/<int:pk>/", ParticipantFormView.as_view(), name="form"),
    path("confirm/", TemplateView.as_view(template_name="contest/confirmEmail.html"), name="confirm"),
    path('success_form/', TemplateView.as_view(template_name="contest/moderation.html"), name="moderation"),
    path('inside/<int:pk>/more/<int:np>/', AdditionalView.as_view(), name="mores"),
    path('export_excel/<int:pk>/', export_excel, name='excel'),
    path('export_excel2/<int:pk>/', export_excel2, name='excel'),
    
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='account/pass_reset.html'),
         name='reset_password'),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/send_email_confirm.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/pass_reset_form.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/pass_reset_done.html'),
         name='password_reset_complete'),
]

natgeo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('', include("main.urls")),
    path('verification/', include('verify_email.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('i18n/',  include('django.conf.urls.i18n')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import uuid
import os
from ckeditor.fields import RichTextField
from django.utils.safestring import mark_safe


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/', instance.__class__.__name__, filename)


class Contest(models.Model):
    title = models.CharField(max_length=255, verbose_name="Имя конкурса")
    photo = models.ImageField(
        upload_to=get_file_path, default=None, verbose_name="Фотография конкурса"
    )
    start_date = models.DateField(verbose_name="Время начало конкурса")
    end_date = models.DateField(verbose_name="Время окончания конкурса")
    description = RichTextField(verbose_name="Описание конкурса")

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return f"/inside/{self.id}/"

    def get_excel(self):
        return mark_safe('<a href="%s">Скачать отчет</a>' % f'/export_excel/{self.id}/')

    get_excel.short_description = 'Отчеты'
    get_excel.allow_tags = True

    @property
    def is_active(self):
        return self.start_date <= datetime.now().date() <= self.end_date

    @property
    def coming(self):
        return datetime.now().date() < self.start_date

    class Meta:
        verbose_name = "Конкурс"
        verbose_name_plural = "Конкурсы"
        ordering = ["-start_date", "end_date"]


class Participant(models.Model):
    PARTICIPANT_TYPE = [(1, "Номинанты"), (2, "Фавориты")]

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author", verbose_name="Автор"
    )
    phone_number = models.ForeignKey("PhoneNumber", on_delete=models.CASCADE, blank=True, null=True)
    contest = models.ForeignKey(
        Contest,
        on_delete=models.CASCADE,
        related_name="contest",
        verbose_name="Конкурс",
    )
    participant_type = models.IntegerField(
        choices=PARTICIPANT_TYPE, default=1, verbose_name="Типы участников"
    )

    def get_absolute_url(self):
        return f"participant/{self.id}/"

    @property
    def drop(self):
        return "SEPTEMBER"

    class Meta:
        verbose_name = "Участник"
        verbose_name_plural = "Участники"

    @property
    def main_image(self):
        if self.photo.count() > 0:
            return self.photo.first().image.url
        return ""

    def __str__(self):
        return self.author.username


class Tags(models.Model):
    tag = models.CharField(max_length=255, verbose_name="Номинации", null=True)

    def __str__(self):
        return f'{self.tag}'

    class Meta:
        verbose_name = "Номинация"
        verbose_name_plural = "Номинации"


class ContestMore(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE, verbose_name="Конкурс")
    title = models.CharField(max_length=255, verbose_name="Имя дополнительного меню")
    description = RichTextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Дополнительная меню"
        verbose_name_plural = "Дополнительные меню"


class ParticipantImages(models.Model):
    POSITION = [(1, "1-е место"), (2, "2-е места"), (3, "3-е места"), (4, None)]
    nominees = models.ForeignKey(
        Participant,
        on_delete=models.CASCADE,
        related_name="photo",
        verbose_name="Работа участника",
    )
    title = models.CharField(max_length=255, verbose_name="Название картины")
    image = models.ImageField(upload_to=get_file_path, verbose_name="картинки")
    is_active = models.BooleanField(verbose_name="Публиковать", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Добавлено")
    position = models.IntegerField(
        choices=POSITION, default=4, verbose_name="Позиции участников"
    )
    tags = models.ForeignKey(
        Tags, on_delete=models.CASCADE, related_name="tags", null=True, blank=True, verbose_name="Номинация"
    )
    description = models.TextField(verbose_name="Описание", null=True, blank=True, default=None)


    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Работы"

    def __str__(self):
        return str(self.nominees)
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % self.image.url)
    image_tag.short_description = 'Работа'
    image_tag.allow_tags = True


class ParticipantUserLike(models.Model):
    nominees = models.ForeignKey(
        ParticipantImages, on_delete=models.CASCADE, related_name="like"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")


class Footer(models.Model):
    name = models.CharField(max_length=255, verbose_name="Футер")
    number_for_ordering = models.PositiveIntegerField(default=0, verbose_name='Номер по счету')

    class Meta:
        verbose_name = "Столбец Футера"
        verbose_name_plural = "Столбцы Футера"
        ordering = ['number_for_ordering']

    def __str__(self):
        return f"{self.name}"


class FooterDetail(models.Model):
    name = models.CharField(max_length=255, verbose_name="Детали футера")
    path = models.CharField(max_length=255, verbose_name="URL")
    detail = models.ForeignKey(Footer, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Данные столбца Футера"
        verbose_name_plural = "Данные столбцов Футера"


class PhoneNumber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=255)

    def __str__(self):
        return self.phone_number

main/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Participant, Tags, PhoneNumber
from django import forms
from django.core.exceptions import ValidationError


class ParticipantsForm(forms.Form):
    image_1 = forms.ImageField(label="Работа #1")
    work_1 = forms.CharField(label="Название Работы")
    tag_1 = forms.ModelChoiceField(queryset=Tags.objects.all(), required=False, label="Тэг")
    description_1 = forms.CharField(label="Описание", widget=forms.Textarea, max_length=300)
    image_2 = forms.ImageField(label="Работа #2", required=False)
    work_2 = forms.CharField(label="Название Работы", required=False)
    tag_2 = forms.ModelChoiceField(queryset=Tags.objects.all(), label="Тэг", required=False)
    description_2 = forms.CharField(label="Описание", required=False, widget=forms.Textarea)
    image_3 = forms.ImageField(label="Работа #3", required=False)
    work_3 = forms.CharField(label="Название Работы", required=False)
    tag_3 = forms.ModelChoiceField(queryset=Tags.objects.all(), label="Тэг", required=False)
    description_3 = forms.CharField(label="Описание", required=False, widget=forms.Textarea)
    image_4 = forms.ImageField(label="Работа #4", required=False)
    work_4 = forms.CharField(label="Название Работы", required=False)
    tag_4 = forms.ModelChoiceField(queryset=Tags.objects.all(), label="Тэг", required=False)
    description_4 = forms.CharField(label="Описание", required=False, widget=forms.Textarea)
    image_5 = forms.ImageField(label="Работа #5", required=False)
    work_5 = forms.CharField(label="Название Работы", required=False)
    tag_5 = forms.ModelChoiceField(queryset=Tags.objects.all(), label="Тэг", required=False)
    description_5 = forms.CharField(label="Описание", required=False, widget=forms.Textarea)

    def clean(self):
        cleaned_data = super(ParticipantsForm, self).clean()
        data = self.cleaned_data
        tags = {'tag_1': '', 'tag_2': '', 'tag_3': '', 'tag_4': '', 'tag_5': ''}
        check_work = any([data[f"work_{i}"] for i in range(1, 6)])
        check_description = any([data[f"description_{i}"] for i in range(1, 6)])
        check_image = any([data[f"image_{i}"] for i in range(1, 6)])
        check_tag = any([data[f'tag_{i}'] for i in range(1, 6)])
        if check_tag:
            tags['tag_1'] += data['tag_1'].tag
        if not check_image or not check_work or not check_description:
            self.add_error("work_1", "Заполните хотя бы одну работу полностью")
        if data['image_1'].size > 600000:
            self.add_error('image_1', "Размер файла должен быть не более 600 КБ")
        for i in range(2, 6):
            if data[f"image_{i}"] is not None:
                if data[f'tag_{i}'] is not None:
                    tags[f'tag_{i}'] += data[f'tag_{i}'].tag
                if data[f'image_{i}'].size > 600000:
                    self.add_error(f"image_{i}", "Размер файла должен быть не более 600 КБ")
                if data[f"description_{i}"] == '':
                    self.add_error(f"description_{i}", 'Без описания мы не сможем принять работу:(')
                if data[f"work_{i}"] == '':
                    self.add_error(f"work_{i}", "Без названия мы не сможем принять работу:(")
        tag_list = []
        tag_dict = {}
        for k, v in tags.items():
            if tags[k] != '':
                tag_list.append(tags[k])
        for item in tag_list:
            tag_dict[item] = tag_list.count(item)
        for k, v in tag_dict.items():
            if tag_dict[k] >= 3:
                self.add_error("tag_3", "По условиям конурса вы можете, на одну номинацию только 2 "
                                         "фотографии")
        return cleaned_data


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=255, label="Қолданушының аты")
    phone = forms.CharField(max_length=11, widget=forms.NumberInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "phone", "email", "password1", "password2"]

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        phone = self.cleaned_data.get('phone')
        if PhoneNumber.objects.filter(phone_number=phone):
            self.add_error('phone', "Такой номер уже используется")
        if User.objects.filter(email=email).exists():
            self.add_error('email', 'Такая почта уже зарегистрирована')
        if User.objects.filter(username=username).exists():
            self.add_error('username', "Такой аккаунт уже есть")
        return cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, label="Имя пользователя")
    password = forms.CharField(
        max_length=255, label="Пароль", widget=forms.PasswordInput()
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        print("check")
        if not User.objects.filter(username=username).exists():
            self.add_error('username', 'Такого аккаунта не существует')
        return cleaned_data

    class Meta:
        model = User
        fields = "__all__"

templates/contest/acc_active_email.html
{% autoescape off %}
Құрметті {{ user }},
мына сілтеме арқылы өтіп тіркелуіңізді растаңыз, https://www.{{ domain }}{% url 'activate' uidb64=uid token=token %}

Уважаемый(-ая) {{ user }},
пройдите по ссылке и подтвердите свой страницу, https://www.{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/contest/base.html
{% load font_awesome %}
{% load i18n %}
{% block additional_style %}
    <style>
    .upper_pos{
        background: url("{{ data.photo.url }}");
    }
    </style>
{% endblock additional_style %}
{% block inside %}
        <div class="main_position">
			<div class="upper_pos">
				<div class="contest_tag">
					{% trans "КОНКУРС" %}
				</div>
				<div class="contest_title">
                    {{ data.title }}
				</div>
				<div class="contest_date">
					{{ data.start_date }}-{{ data.end_date }}
				</div>
                {% if data.is_active and data.coming is False %}
				<div class="contest_ending">
                    {% trans "Активный конкурс" %}
                    {% if user.is_authenticated and user.email != '' %}
                    <a href="{% url 'form' data.id %}" class="btn_invite" id="invite" data-url="" >{% trans "Принять участие" %}</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn_invite" id="invite" data-url="" > {% trans "Принять участие" %}</a>
                    {% endif %}
                </div>
                {% elif data.is_active is False and data.coming is False %}
                <div class="contest_ending">
                {% blocktrans %}Этот конкурс уже закончился, но скоро будут новые!{% endblocktrans %}
				</div>
                {% elif data.is_active is False and data.coming %}
                 <div class="contest_ending">
                 
				</div>
                {% endif %}
            </div>
            <div class="under_pos">
                {% if data.is_active %}
				    <a href="{% url 'inside' data.id%}" class="changing_links">{% trans "О конкурсе" %}</a>
                    {% if more.count == 0 %}
                    <a href="{% url 'nominee' data.id %}" class="changing_links last">{% trans "Работы участников" %}</a>
                    {% else %}
                    <a href="{% url 'nominee' data.id %}" class="changing_links">{% trans "Работы участников" %}</a>
                    {% endif %}
                {% elif data.is_active is False and data.coming is True %}
				    {% if more.count == 0 %}
				        <a href="{% url 'inside' data.id%}" class="changing_links last">{% trans "О конкурсе" %}</a>
                    {% else %}
				        <a href="{% url 'inside' data.id%}" class="changing_links">{% trans "О конкурсе" %}</a>
                    {% endif %}
                {% elif data.is_active is False and data.coming is False%}
				    <a href="{% url 'inside' data.id%}" class="changing_links">{% trans "О конкурсе" %}</a>
                    <a href="{% url 'nominee' data.id %}" class="changing_links">{% trans "Работы участников" %}</a>
                    {% if more.count == 0 %}
                        <a href="{% url 'winners' data.id%}" class="changing_links last">{% trans "Победители" %}</a>
                    {% else %}
                      <a href="{% url 'winners' data.id%}" class="changing_links">{% trans "Победители" %}</a>
                    {% endif %}
                {% endif %}
                {% for i in more %}
                    {% if forloop.counter == more.count %}
                    <a href="{% url 'mores' data.id i.id %}" class="changing_links last">{{ i }}</a>
                     {% else %}
                    <a href="{% url 'mores' data.id i.id %}" class="changing_links">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                </div>
		</div>
{% endblock inside %}

templates/contest/confirmEmail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container messages" style="height: 100%;display: flex;justify-content: center;align-items: center;">
        <div class="main_position_form">

            <h1>{% trans "Пожалуйста подтвердите аккаунт, зайдя на почту" %}</h1>

            <a href="{% url 'homepage' %}" type="button" class="btn_invite" id="invite" data-url="" >{% trans "Вернуться" %}</a>

        </div>
    </div>
{% endblock content %}

templates/contest/favorites.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="container">
		{% include 'contest/base.html' %}
		<div class="bottom_wrapper">

			<div class="page_content">
				<div class="title_page_mini">
					{% trans "Фавориты" %}
				</div>
				<div class="nominees_filter">
					<div class="nominees_filter_element active" data-order="">
						<a href="">{% trans "Новые" %}</a>
					</div>
					<div class="nominees_filter_line nominees_filter_line_left"></div>
					<div class="nominees_filter_element" data-order="order=popular">
						<a href="">{% trans "Популярные" %}</a>
					</div>
				</div>
                <div class="row">
                    {% for nom in favorites %}
                    <div class="col-md-4 col-sm-6 col-12">
                        <a href="{% url 'nominee_detail' nom.id %}">
                            <div class="cards">
                                <img src="{{ nom.main_image }}" alt="photo">
                                <div class="inside_text">
                                    {{ nom.author }}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
		</div>
	</div>
{% endblock content %}

templates/contest/form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data" class="for_me">
            {% csrf_token %}
            {% for field in form %}
                {% if field.field.required %}
                    <span class="required">{{ field.label }}*</span>
                       {{ field }}
                {% else %}
                    {{ field.label }} {{ field }}
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
                {% endfor %}
            <div class="g-recaptcha" data-sitekey="{{ SECRET_KEY }}"></div>
            <input href="" type="submit" class="btn_invite btn_invite_form" id="invite" data-url="" value="{% trans "Принять участие" %}"/>
            <div class="input-group">
        </div>
        </form>
    </div>
{% endblock %}

templates/contest/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    	<div class="container index_container" style="height:max-content;">

		<div class="contest">
			<div class="title_page">
				{% trans "Конкурсы" %}
			</div>

			<div class="row">
                {% for contest in contests %}
				<div class="col-md-4 col-sm-6 col-12" style="height: 400px">
					<a href="{% url 'inside' contest.id %}">
						<div class="cards">
							<img src="{{ contest.photo.url }}" alt="photo">
							{% if contest.is_active and contest.coming is False %}
                                <div class="status" style="color: lime; z-index: 2;">
                                    {% trans "Активный конкурс" %}
                                </div>
                            {% elif contest.is_active is False and contest.coming %}
                                <div class="status">
								    {% trans "Будущий конкурс" %}
                                </div>
                            {% elif contest.is_active is False and contest.coming is False %}
                                <div class="status">
								    {% trans "Завершен" %}
                                </div>
                            {% endif %}
							<div class="inside_text_in_index">
                                {{ contest.title }}
							</div>
							<div class="date">
								{{ contest.start_date }}<br>{{ contest.end_date }}
							</div>
						</div>
					</a>
				</div>
                {% endfor %}




			</div>
		</div>

	</div>

{% endblock content %}

templates/contest/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container special_login">
        <div class="centering">

            <h1>{% trans "ВОЙТИ" %}</h1>
            <p>{% trans "Если вы не зарегистрированы, вы можете" %}<a href="{% url 'signup' %}"> {% trans "присоединиться к нам" %}</a> {% trans "прямо сейчас" %}.</p>
            <p><a href="{% url 'reset_password' %}">{% trans "Забыли пароль?" %}</a></p>
            <form class="login" action="{% url 'login' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="id_username">{% trans "Имя пользователя:" %}</label>
                {{ form.username }}
                <label for="id_password">{% trans "Пароль:" %}</label>
                {{ form.password }}
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                            <strong>{{ field.errors }}</strong>
                            {% endfor %}
                        </div>
                    {% endif %}
                <input class="primaryAction login-input" type="submit" value="{% trans "ВОЙТИ" %}">
            </form>
        </div>
    </div>
{% endblock content %}

templates/contest/moderation.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container messages" style="height: 100%;display: flex;justify-content: center;align-items: center;text-align: center;">
        <div class="main_position_form">
            <h1>{% trans "Ваша работа принята!" %}
                <br>
                {% trans "После модерации будет опубликована на сайте!" %}
            </h1>
            <a href="{% url 'homepage' %}" type="button" class="btn_invite" id="invite" data-url="" >{% trans "Вернуться" %}</a>
        </div>
    </div>
{% endblock content %}

templates/contest/nomineeInside.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load font_awesome %}
{% fa_css %}
{% block content %}
    <div class="container">
		<div class="main_position">
			<div class="upper_pos nominees_inside" style="height: 1px;">
                <div class="swiper-slide">
							<div class="slider_inner">
								<a class="fancy_images" oncontextmenu="return false;"><img src="{{ object.image.url }}" alt="" oncontextmenu="return false;"/></a>
							</div>
						</div>
				</div>
			</div>
			<div class="under_pos_like">
                     <div id="like-button">
                     {% if object.nominees.contest.is_active %}
                         {% if is_active_like_button %}
					        <button type="button" class="btn_like" id="like" data-url="{% url 'like_nominee' object.id %}"><i class="fas fa-thumbs-up"></i></button>
				         {% else %}
                            <button type="button" disabled class="btn_like" id="like" data-url="{% url 'like_nominee' object.id %}"> <i class="fas fa-thumbs-up"></i></button>
                         {% endif %}
                     {% else %}

                     {% endif %}
                     </div>
		</div>
		<div class="bottom_wrapper">
            <div class="links_wrapper">
				<a href="https://www.facebook.com/sharer/sharer.php?u=https://natgeo-photocontest.kz{{ request.get_full_path }}src=sdkpreparse" class="share_links" target="_blank">
					<div class="share-icon">
						<div class="icon_itself">
							<i class="fab fa-facebook"></i>
						</div>
					</div>
				</a>
				<a href="https://vk.com/share.php?noparse=true&image=https://natgeo-photocontest.kz{{object.image.url}}&url=https://natgeo-photocontest.kz{{ request.get_full_path }}" class="share_links" target="_blank">
					<div class="share-icon">
						<div class="icon_itself">
                            <i class="fab fa-vk"></i>
						</div>
					</div>
				</a>			
				<a href="http://twitter.com/share?text=&url=https://natgeo-photocontest.kz{{ request.get_full_path }}" class="share_links" target="_blank">
					<div class="share-icon">
						<div class="icon_itself">
							<i class="fab fa-twitter"></i>
						</div>
					</div>
				</a>	
				<a href="https://connect.ok.ru/offer?url=https://natgeo-photocontest.kz{{ request.get_full_path }}" class="share_links" target="_blank">
					<div class="share-icon">
						<div class="icon_itself">
							<i class="fab fa-odnoklassniki"></i>
						</div>
					</div>
				</a>				
			</div>

			<div class="page_content_title">
                {{ object.title }}
			</div>
			<div class="author_info_inside">
				<a href="{% url 'users' object.nominees.author.id %}" class="author_info_name">
					{{ object.nominees.author.first_name }}
					{{ object.nominees.author.last_name }}
				</a>
				<div class="author_info_int">
					<div class="author_info_date">{{ object.created.date }}</div>
				</div>
			</div>
			{% if object.description != None %}
            <div class="page_content_text">
                {{ object.description }}
			</div>
        	{% endif %}
            {% if object.position != 4  %}
                {% if object.nominees.contest.is_active is False and object.nominees.contest.coming is False %}
                    <div class="favorite">
                        <div class="favorite_icon">
                            <img src="{% static 'images/cup.svg' %}" alt=""/>
                        </div>
                        <p>
                            {{ object.get_position_display }} {% trans "конкурса" %}
                            <a href="{% url 'inside' object.nominees.contest.id %}">{{ object.nominees.contest }}</a>
                        </p>
                    </div>
                {% endif %}
            {% endif %}

            </div>
			<script>
				$("a.fancy_images").fancybox();
				$("a.fancy_images").contextmenu(function() {
  				alert( "Handler for .contextmenu() called." );
				  );
			</script>
{% endblock content %}

{% block script %}
    <script>
    $("#like").click(function(){
        $.ajax({
            url: $(this).data('url'),
            type: 'get',
            success: function(result) {
                alert(result.status)
                console.log($(this));
                $("#like").attr('disabled', "")
            }
        });
    });
    var swiper = new Swiper('.swiper-container', {
			navigation: {
				nextEl: '.swiper-button-next',
				prevEl: '.swiper-button-prev',
			},
		});
    </script>

{% endblock script %}

templates/contest/registration.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="container special_login">
        <div class="centering">

            <h1>{% trans "Регистрация" %}</h1>
            <p>{% trans "Если у вас есть аккаунт, можете" %} <a href="{% url 'login' %}">{% trans "зайти" %}</a>.</p>

            <form action="{% url 'signup' %}" class="signup" id="signup_form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label for='id_username'>{% trans "Логин:" %}</label>
                {{ form.username }}
                <label for="id_firstname">{% trans "Имя пользователя:" %}</label>
                {{ form.first_name }}
                <label for="id_lastname">{% trans "Фамилия пользователя:" %}</label>
                {{ form.last_name }}
                <label for="id_email">{% trans "Адрес электронной почты:" %}</label>
                {{ form.email }}
                <label for="id_phone">{% trans "Номер телефона:" %}</label>
                {{ form.phone }}
                <label for="id_password1">{% trans "Пароль:" %}</label>
                {{ form.password1 }}
                <label for="id_password2">{% trans "Подтверждение пароля:" %}</label>
                {{ form.password2 }}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for field in form %}
                        <strong>{{ field.errors }}</strong>
                        {% endfor %}
                    </div>
                {% endif %}
                <input class="go_register" type="submit" value="{% trans "Зарегистрироваться" %}">
            </form>
        </div>
    </div>
{% endblock content %}